--- 
javascripts:
- location:
  - jquery
  - jquery-form
  - jquery-color
  - location-comment 
- base: 
  - ym4r-mapstraction
  - new-time
  - mapstraction
  - location-comment
  - jquery
  - jquery-form
  - jquery-color
  - comment-form
  - clusterer
  - application
stylesheets: 
- base: 
  - admin
  - all
  - basic
  - frontpage
  - scaffold
