development:
  adapter: mysql
  database: wifi_development
  username: root
  password: james

test: &test
  adapter: mysql
  database: wifi_test
  username: root
  password: james

cucumber:
  <<: *test
