development:
  adapter: mysql
  host: localhost
  username: root
  password: 
  database: wifi_development

test:
  adapter: mysql
  host: localhost
  username: root
  password: 
  database: wifi_test
